// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpcotIWmf3uLFdy1ARby9Lv1FG6VrPV8',
    appId: '1:519881022529:web:495c51a27af3c9656afac0',
    messagingSenderId: '519881022529',
    projectId: 'batch2208e-769d2',
    authDomain: 'batch2208e-769d2.firebaseapp.com',
    databaseURL: 'https://batch2208e-769d2-default-rtdb.firebaseio.com',
    storageBucket: 'batch2208e-769d2.appspot.com',
    measurementId: 'G-B0V880137N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nM7Kh71a3hjPkElvjZF5WHDdAzaOzYQ',
    appId: '1:519881022529:android:c111e67e64a4aac46afac0',
    messagingSenderId: '519881022529',
    projectId: 'batch2208e-769d2',
    databaseURL: 'https://batch2208e-769d2-default-rtdb.firebaseio.com',
    storageBucket: 'batch2208e-769d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9ZGLujvVQ4VKAE8Dd_Vejx8o3RtC1VU',
    appId: '1:519881022529:ios:e4040e94d5cc867d6afac0',
    messagingSenderId: '519881022529',
    projectId: 'batch2208e-769d2',
    databaseURL: 'https://batch2208e-769d2-default-rtdb.firebaseio.com',
    storageBucket: 'batch2208e-769d2.appspot.com',
    iosBundleId: 'com.example.flutterProject2208e',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9ZGLujvVQ4VKAE8Dd_Vejx8o3RtC1VU',
    appId: '1:519881022529:ios:e4040e94d5cc867d6afac0',
    messagingSenderId: '519881022529',
    projectId: 'batch2208e-769d2',
    databaseURL: 'https://batch2208e-769d2-default-rtdb.firebaseio.com',
    storageBucket: 'batch2208e-769d2.appspot.com',
    iosBundleId: 'com.example.flutterProject2208e',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6oBuntPITwxjtXOVuwWvISIvrZSfn9II',
    appId: '1:519881022529:web:90281032bdb95dd36afac0',
    messagingSenderId: '519881022529',
    projectId: 'batch2208e-769d2',
    authDomain: 'batch2208e-769d2.firebaseapp.com',
    databaseURL: 'https://batch2208e-769d2-default-rtdb.firebaseio.com',
    storageBucket: 'batch2208e-769d2.appspot.com',
    measurementId: 'G-TQVP7SS6FQ',
  );
}
